# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14LxIwfaFOgt-8jbFwaQ_iawwmRHz0oMT
"""

import seaborn as sns
import matplotlib.pyplot as plt

def categorical_histogram(df):

    pas_col = df.columns[[2, 5, 6, 7, 9, 13,8,11,12]]
    """
    Histograms for categorical variables in the dataset.

    Parameters
    ----------
    df : pd.DataFrame
        Input data to generate plots.

    """
    for colonne in df.columns:
        if colonne not in pas_col:
            plt.figure(figsize=(15, 5))
            sns.countplot(x=colonne, data=df, palette='viridis')

            plt.title(f'Distribution des modalités dans {colonne}')
            plt.xlabel('Modalité')
            plt.ylabel('Fréquence')
            plt.show()
